### ISSUE TITLE
Remove paper from repo

### ISSUE THREAD

**Issue by mdfeist** [mdfeist/TypeV#40]
If the paper is submitted and accepted then we probably shouldn't have it posted on our GitHub.

**Comment by eddieantonio** [comment]
It depends on how you handle the copyright agreement with the publisher. You can transfer rights, which I wouldn't recommend; alternatively, you could license the paper for publication, in which case --- unless they have some weird clause against it, we can keep the source here on GitHub.

**Comment by eddieantonio** [comment]
According to Abram, it's okay for our TeX sources to be on GitHub. Apparently, IEEE will force us to transfer distribution rights of the published paper itself, and thus, we cannot freely post a PDF copy of our paper once it has been published. That said, our TeX sources are fair game.

I added an explicit license to our paper directory as of 4ac6dd6. This is the CC-By-ND 4.0 license which permits all redistribution, but disallows derivatives. This effectively forces anybody extending our work to cite our paper rather than simply taking our paper, changing the source a bit, and slapping their name on it.

As the license is present, I'm marking this as closed.
